language: go
sudo: false
addons:
  postgresql: 9.4
go:
  - 1.4
  - tip
cache:
  directories:
  - samples
install:
  - go get github.com/codegangsta/cli
  - go get github.com/lib/pq
  - go get github.com/kennygrant/sanitize
  - go get github.com/cheggaaa/pb
  - ./download_samples.sh
script:
  - go install && ./test.sh
